require("busted.runner")()

local solution = require "solution"

describe("ValidBraces", function()
  it("ShouldPassBasicTests", function()
    assert.True(solution.validBraces("(){}[]"))
    assert.True(solution.validBraces("()"))
    assert.False(solution.validBraces("[(])"))
    assert.True(solution.validBraces("([{}])"))
    assert.False(solution.validBraces("())"))
    assert.False(solution.validBraces("(}"))
    assert.False(solution.validBraces("){"))
    assert.False(solution.validBraces("[(])"))
    assert.False(solution.validBraces("[({})](]"))
  end)
  it("ShouldPassAdvancedTests", function()
    assert.True(solution.validBraces("(){}[]"))
    assert.True(solution.validBraces("([{}])"))
    assert.True(solution.validBraces("({})[({})]"))
    assert.True(solution.validBraces("(({{[[]]}}))"))
    assert.True(solution.validBraces("{}({})[]"))
    assert.False(solution.validBraces(")(}{]["))
    assert.False(solution.validBraces("())({}}{()][]["))
    assert.False(solution.validBraces("}}]]))}])"))
  end)
end)
